# -*- coding: utf-8 -*-
"""Seminar10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lNq-EWwMAjQgyETxTN-xYNGvoLwDfIrK
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("/content/sample_data/california_housing_test.csv")

# from google.colab import drive
# drive.mount('/content/gdrive', force_remount=True)

"""##Задача №63. Решение в группах

1. Изобразите отношение households к population с
помощью точечного графика
"""

plt.figure(figsize=(16,10))
sns.scatterplot(df, x='households', y='population');

"""2. Визуализировать longitude по отношения к
median_house_value, используя линейный график
"""

sns.relplot(df, x='longitude', y='median_house_value', kind='line');
# sns.lineplot(df, x='longitude', y='median_house_value');

"""
3. Представить гистограмму по housing_median_age"""

sns.histplot(df, x='housing_median_age')

"""4. Изобразить гистограмму по median_house_value с
оттенком housing_median_age
"""

plt.figure(figsize=(16, 10))
sns.histplot(df, x='median_house_value', hue='housing_median_age')
plt.xticks(range(0, 550000, 25000), rotation=45)
plt.yticks(range(0, 26, 1));

"""##Задача №65. Решение в группах

Написать EDA для датасета про пингвинов
Необходимо:

● Использовать 2-3 точечных графика

● Применить доп измерение в точечных графиках, используя
аргументы hue, size, stile

● Использовать PairGrid с типом графика на ваш выбор

● Изобразить Heatmap

● Использовать 2-3 гистограммы
"""

penguins = sns.load_dataset("penguins")
penguins.sample(20)

sns.scatterplot(penguins, x='bill_length_mm', y='bill_depth_mm', size='sex', style='island');

sns.scatterplot(penguins, x='flipper_length_mm', y='body_mass_g', hue='species', size='sex', style='island');

sns.scatterplot(penguins, x='bill_length_mm', y='body_mass_g', hue='species', size='sex', style='island');

Adelie=penguins[penguins['species'] == 'Adelie']

sns.scatterplot(Adelie, x='bill_length_mm', y='body_mass_g', style='island', s=50);

g = sns.PairGrid(penguins[['bill_depth_mm','bill_length_mm', 'body_mass_g', 'flipper_length_mm',]])
g.map(sns.scatterplot)

corr_pg = penguins.corr()
corr_pg

sns.heatmap(corr_pg, annot=True, cmap='coolwarm', linewidths=1)

sns.histplot(penguins, x='bill_length_mm');

sns.histplot(penguins, x='body_mass_g');

sns.histplot(penguins, x='flipper_length_mm');

"""##Задача №67. Решение в группах

1. Создать новый столбец в таблице с
пингвинами, который будет отвечать за
показатель длины клюва пингвина.

high - длинный(от 42)

middle - средний(от 35 до 42)

low - маленький(до 35)
"""

penguins.loc[penguins['bill_length_mm'] >= 42, 'high_group'] = 'high'
penguins.loc[(penguins['bill_length_mm'] >= 35) & (penguins['bill_length_mm'] < 42), 'high_group'] = 'middle'
penguins.loc[penguins['bill_length_mm'] < 35, 'high_group'] = 'low'

"""##Задача №69. Решение в группах

1. Изобразить гистограмму по flipper_length_mm
с оттенком height_group.
 Сделать анализ
"""

sns.histplot(penguins, x='flipper_length_mm', hue='high_group')